version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - misspell

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment

  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor/
    - third_party/
    - generated/
    - mock/
    - web/
    - docs/
    - .git/

  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
